### PR TITLE
Update ELK_Stack_Multi_AZ_in_Private_VPC.yml

### PR DESCRIPTION
**Pull request by dbgdngit**
The default public access port should be https not http.

### CODE REVIEW

**Comment by adamnfish** [comment]
This change looks good for you now. However, it does break it the other way round and on further inspection I've spotted this:
https://github.com/dbgdngit/elk-stack/blob/12e7e7d941e58ffb78674159a80d3bda385a7f8d/cloudformation/ELK_Stack_Multi_AZ_in_Private_VPC.yml#L275

It's probably worth doing the same thing here? I'd consider pulling that out into a template variable (mapping) and then referring to that in a few places. So create a port 'variable' that is 443 is a cert was provided and 80 otherwise. You can then refer to that here and elsewhere in the template (see above).

[Here's the mappings in the template](https://github.com/dbgdngit/elk-stack/blob/12e7e7d941e58ffb78674159a80d3bda385a7f8d/cloudformation/ELK_Stack_Multi_AZ_in_Private_VPC.yml#L114)
[and here's a usage](https://github.com/dbgdngit/elk-stack/blob/12e7e7d941e58ffb78674159a80d3bda385a7f8d/cloudformation/ELK_Stack_Multi_AZ_in_Private_VPC.yml#L342)

So something like:

```yaml
Mappings: <-- in the template's existing mappings object
  Constants:
    PublicELBPort:
      Value:
        Fn::If:
        - HasSSLCertificate
        - '443'
        - '80'
```

and then:
```yaml
FromPort: !FindInMap [ Constants, PublicELBPort ]
ToPort: !FindInMap [ Constants, PublicELBPort ]
```

It looks like this should have been there before, it's a mistake in the template that it isn't doing this test already, so I'd consider raising this PR against master to fix it for everyone!

**Comment by TBonnin** [comment]
This is definitely a mistake. There is no reason why the check should be done for the ELB listeners but not for the Security Group.
@adamnfish fix is probably the best way to deal with it.

**Comment by adamnfish** [comment]
I had a quick look but sadly Mappings have to be simple values. Just means that logic will be duplicated in a few places, I'll try and get to that today, thanks @TBonnin

**Comment by adamnfish** [comment]
https://github.com/guardian/elk-stack/pull/71

**Comment by adamnfish** [comment]
This is redundant now that #71 is merged, so I'll close it.

**Pull request closed without merging**
