### PR TITLE
Bump up dependencies - Snyk

### PR DESCRIPTION
**Pull request by jbguardian**
Snyk summary:

**HIGH SEVERITY**
- Vulnerable module: qs -Remediation: Upgrade to request@2.40.0.
- Vulnerable module: negotiator - Remediation: Upgrade to express@4.0.0.
- Vulnerable module: fresh - Remediation: Upgrade to express@4.15.5.

**MEDIUM SEVERITY**
- Vulnerable module: qs - Remediation: Upgrade to request@2.40.0.
- MPL-2.0 license - pending to confirm
- Vulnerable module: request - Remediation: Upgrade to request@2.68.0.
- Vulnerable module: http-signature - Remediation: Upgrade to request@2.66.0.
- Vulnerable module: tunnel-agent - Remediation: Upgrade to request@2.81.0.

**LOW SEVERITY**
- Vulnerable module: hoek - Remediation: Upgrade to **request@2.82.0**.
- Vulnerable module: hawk - Remediation: Upgrade to request@2.59.0.
- Vulnerable module: ms - Remediation: Upgrade to express@4.15.3.
- Vulnerable module: mime - Remediation: Upgrade to request@2.37.0 - **express@4.16.0**
- Vulnerable module: debug - Remediation: Upgrade to express@4.15.5.

### CODE REVIEW

**Comment by johnduffell** [comment]
thanks, @AWare may be able to give input on the client side stuff

As mentioned, this app is hopefully being replaced hopefully be a shared department stac in the longer term.

re deployment I have a feeling we can deploy by just recycling the instances one at a time and waiting for the data to sync.

 I think dotcom platform may be using this elk stack too @stephanfowler @nicl so may also be interested in the updates.  Not sure if anyone else is.

**Comment by jfsoul** [comment]
Identity use this repo too for future reference, but I found this PR anyway 👀

**Comment by AWare** [comment]
We should consider replacing the node_app with https://github.com/bitly/oauth2_proxy

**Comment by johnduffell** [comment]
yes, I considered that too, but I struggling (about a year ago!)  if we are going to keep this app or even front onto a hosted ES/kibana, then that's important.  good suggestion.

**Pull request merged**
